name: Deployment
concurrency: production
on:
  workflow_dispatch
  # push:
  #  branches:
  #    - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.0
      with:
        # Repository name with owner. For example, actions/checkout
        repository: ${{ github.repository }}
        # The branch, tag or SHA to checkout. When checking out the repository that triggered a workflow, this defaults to the reference or SHA for that event.  Otherwise, uses the default branch.
        # ref: # optional
        fetch-depth: 1
        # Whether to fetch tags, even if fetch-depth > 0.
        fetch-tags: true
        # Whether to show progress status output when fetching.
        show-progress: false
    - name: List files
      run: |
        ls -lrt
    - name: Publish PowerShell Module
      # You may pin to the exact commit or the version.
      # uses: pcgeek86/publish-powershell-module-action@2a7837ce0746ea58c40574d8d6cbc6c44238edb7
      uses: pcgeek86/publish-powershell-module-action@v20
      with:
        # The filesystem path to the module to import into the environment.
        modulePath: ./ExoReports
        # The NuGet API Key for PowerShell Gallery, with permission to push this module.
        NuGetApiKey: ${{ secrets.PS_GALLERY_KEY }}
